name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install poetry
          poetry install
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi
      - name: Test with pytest
        run: |
          pytest -x --cov=olxbrasil --cov-report term-missing --cov-branch tests/