name: Publish to Pypi

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1
        with:
          python_version: '3.9.2'
          poetry_version: '==1.1.5'  # (PIP version specifier syntax)
          pypi_token: ${{ secrets.PYPI_TOKEN }}